import streamlit as st
from streamlit_mic_recorder import speech_to_text
from utils.assistant import generate_answer, text_to_speech

# --------------------------------------------------
# Page Configuration
# --------------------------------------------------
st.set_page_config(
    page_title="Strait of Hormuz - Unblocked",
    page_icon="💜",
    layout="centered"
)

# --------------------------------------------------
# Styling
# --------------------------------------------------
st.markdown("""
<style>
.stApp {
    background: linear-gradient(180deg, #000000 0%, #0d061a 100%);
    color: #ffffff;
}

.title {
    text-align: center;
    font-size: 2.8rem;
    font-weight: 700;
    color: #D4AF37;
    margin-top: 2rem;
    margin-bottom: 0.5rem;
    letter-spacing: 0.5px;
}

.subtitle {
    text-align: center;
    color: #d8cfa0;
    font-size: 1rem;
    margin-bottom: 2rem;
}

.response {
    background: rgba(20, 10, 35, 0.92);
    border: 1px solid rgba(212, 175, 55, 0.35);
    border-left: 4px solid #D4AF37;
    border-radius: 20px;
    padding: 1.5rem;
    margin-top: 2rem;
    line-height: 1.8;
    font-size: 1.05rem;
    color: #ffffff;
}

/* Hide any text box generated by the microphone component */
textarea,
input[type="text"] {
    display: none !important;
}
</style>
""", unsafe_allow_html=True)

# --------------------------------------------------
# Header
# --------------------------------------------------
st.markdown(
    '<div class="title">Strait of Hormuz - Unblocked</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">Tap the microphone and ask in Hindi.</div>',
    unsafe_allow_html=True
)

# --------------------------------------------------
# IMPORTANT:
# Render the microphone directly in Streamlit.
# Do not place it inside st.markdown HTML containers.
# --------------------------------------------------
question = speech_to_text(
    language="hi-IN",
    start_prompt="🎙️ Tap to Ask",
    stop_prompt="⏹️ Stop Recording",
    just_once=True,
    use_container_width=True,
    key="voice_input"
)

# --------------------------------------------------
# Generate Response Automatically
# --------------------------------------------------
if question and question.strip():
    with st.spinner("Consulting the heart..."):
        answer = generate_answer(question)

    # Show text answer
    st.markdown(
        f'<div class="response">{answer}</div>',
        unsafe_allow_html=True
    )

    # Generate and autoplay Hindi audio
    try:
        audio_path = text_to_speech(answer)

        with open(audio_path, "rb") as audio_file:
            st.audio(
                audio_file.read(),
                format="audio/mp3",
                autoplay=True
            )
    except Exception as e:
        st.warning(f"Audio playback error: {e}")
